#!/usr/bin/env python
# (Be in -*- python -*- mode.)
#
# ====================================================================
# Copyright (c) 2000-2007 CollabNet.  All rights reserved.
#
# This software is licensed as described in the file COPYING, which
# you should have received as part of this distribution.  The terms
# are also available at http://subversion.tigris.org/license-1.html.
# If newer versions of this license are posted there, you may use a
# newer version instead, at your option.
#
# This software consists of voluntary contributions made by many
# individuals.  For exact contribution history, see the revision
# history and logs, available at http://cvs2svn.tigris.org/.
# ====================================================================

import sys

# Make sure this Python is recent enough.  Do this as early as possible,
# using only code compatible with Python 1.5.2 before the check.
if sys.hexversion < 0x02040000:
  sys.stderr.write("ERROR: Python 2.4 or higher required.\n")
  sys.exit(1)

from cvs2svn_lib.common import FatalException
from cvs2svn_lib.main import main


try:
  main(sys.argv[0], sys.argv[1:])
except FatalException, e:
  sys.stderr.write(str(e) + '\n')
  sys.exit(1)


